### ISSUE TITLE
Cannot start container

### ISSUE THREAD

**Issue by ciB89** [Saberwolf64/Proxmox-Nvidia-LXC-#1]
This is not working for me. 

When starting the container I get the following errors: 

__safe_mount_beneath_at: 1106 Function not implemented - Failed to open 51(dev)
run_buffer: 314 Script exited with status 1
lxc_setup: 3388 Failed to run mount hooks
do_start: 1218 Failed to setup container "102"
__sync_wait: 36 An error occurred in another process (expected sequence number 5)
__lxc_start: 1999 Failed to spawn container "102"
TASK ERROR: startup for container '102' failed

**Comment by maa-x** [comment]
If I had to venture a guess, your container is privileged or you are trying to use privileged features, which do not play well with the nvidia runtime

**Comment by ciB89** [comment]
> If I had to venture a guess, your container is privileged or you are trying to use privileged features, which do not play well with the nvidia runtime

Yes, that was the issue.

**Comment by maa-x** [comment]
Sorry to be a pain, did you by any chance succeed using this and mounting an NFS directory with read/write permissions?

EDIT: I just set the proper options for NFS on the exporting server. I think it's root_squash (Map all users to admin in Synology)
